import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { KeyProvider } from "@/context/KeyContext"; // Import the KeyProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <KeyProvider>{children}</KeyProvider> {/* Wrap children with KeyProvider */}
      </body>
    </html>
  );
}
